"""
Integrity checks for speech recognition models fetched from the internet.

Vocalinux downloads multi-gigabyte model files from Hugging Face, Alphacephei
and OpenAI's CDN and then loads them into the user's process. Three things can
go wrong between "we asked for a model" and "we loaded it", and this module
covers all three:

1. **We fetch from somewhere we did not intend.** ``ensure_trusted_model_url``
   rejects any download URL that is not HTTPS on a known model host, so a bad
   config value or a plain-HTTP redirect cannot silently redirect a download.
2. **We fetch the wrong bytes.** ``verify_downloaded_model`` compares the file
   against the SHA256 digest pinned in ``model_hashes.json``, which catches
   truncated downloads, CDN corruption, TLS-terminating proxies rewriting the
   body, and upstream files being swapped after we recorded them.
3. **Unpacking the model writes outside the models directory.** VOSK models are
   zip archives from a third party, and ``zipfile.extractall`` happily follows
   ``../`` entries. ``safe_extract_zip`` validates every member first.

Pinning proves integrity, not authenticity: a digest recorded from an upstream
file that was already malicious would still match. What it buys us is that the
bytes are reviewed once, in a pull request, and can never change afterwards
without the check failing loudly. Digests are regenerated by
``scripts/update_model_hashes.py``; see SECURITY.md for the threat model.
"""

import hashlib
import json
import logging
import os
import zipfile
from pathlib import Path
from typing import Optional
from urllib.parse import urlparse

logger = logging.getLogger(__name__)

REGISTRY_PATH = Path(__file__).with_name("model_hashes.json")

# Hosts we are willing to download model weights from. Redirect targets are not
# checked against this set (Hugging Face redirects to per-request CDN hostnames);
# the digest check is what protects the redirected response.
TRUSTED_MODEL_HOSTS = frozenset(
    {
        "huggingface.co",
        "alphacephei.com",
        "openaipublic.azureedge.net",
    }
)

# Refuse to unpack an archive that expands to more than this. The largest VOSK
# model is a little over 2 GB unpacked, so this leaves generous headroom while
# still bounding a decompression bomb.
MAX_ARCHIVE_EXPANDED_BYTES = 8 * 1024 * 1024 * 1024

# When set to a truthy value, models with no pinned digest are refused instead
# of being downloaded with a warning.
STRICT_ENV_VAR = "VOCALINUX_STRICT_MODEL_VERIFICATION"

_HASH_CHUNK_BYTES = 1024 * 1024


class ModelIntegrityError(RuntimeError):
    """Raised when a model download fails an integrity check.

    Subclasses RuntimeError so the existing download error handling — which
    cleans up partial files and surfaces the message in the download dialog —
    treats a failed integrity check like any other fatal download error.
    """


def strict_mode_enabled() -> bool:
    """Return True when unpinned models should be refused rather than warned about."""
    return os.environ.get(STRICT_ENV_VAR, "").strip().lower() in {"1", "true", "yes", "on"}


def load_registry() -> dict:
    """Load the pinned digest registry, returning an empty registry on failure."""
    try:
        with open(REGISTRY_PATH, "r") as handle:
            registry = json.load(handle)
    except (OSError, json.JSONDecodeError) as exc:
        logger.error("Could not load model digest registry %s: %s", REGISTRY_PATH, exc)
        return {}
    return registry if isinstance(registry, dict) else {}


def get_pinned_digest(model_type: str, filename: str) -> Optional[dict]:
    """
    Look up the pinned digest for a model file.

    Args:
        model_type: One of "whispercpp", "whisper" or "vosk".
        filename: The downloaded file's name, e.g. "ggml-tiny.bin".

    Returns:
        A dict with "sha256" and "size" keys, or None when the model is unpinned.
    """
    entry = load_registry().get(model_type, {}).get(filename)
    if isinstance(entry, dict) and entry.get("sha256"):
        return entry
    return None


def sha256_file(filepath: str) -> str:
    """Compute the SHA256 digest of a file."""
    digest = hashlib.sha256()
    with open(filepath, "rb") as handle:
        for chunk in iter(lambda: handle.read(_HASH_CHUNK_BYTES), b""):
            digest.update(chunk)
    return digest.hexdigest()


def verify_downloaded_model(
    filepath: str,
    model_type: str,
    filename: str,
    strict: Optional[bool] = None,
) -> None:
    """
    Check a downloaded model against its pinned digest.

    Args:
        filepath: Path to the file that was just downloaded.
        model_type: One of "whispercpp", "whisper" or "vosk".
        filename: Registry key for the model, e.g. "ggml-tiny.bin".
        strict: Refuse unpinned models. Defaults to the value of
            VOCALINUX_STRICT_MODEL_VERIFICATION.

    Raises:
        ModelIntegrityError: If the size or digest does not match the pin, or if
            the model is unpinned and strict verification is enabled.
    """
    if strict is None:
        strict = strict_mode_enabled()

    pinned = get_pinned_digest(model_type, filename)

    if pinned is None:
        message = (
            f"No pinned SHA256 digest for {filename}; its contents cannot be verified. "
            f"Add one with scripts/update_model_hashes.py."
        )
        if strict:
            raise ModelIntegrityError(message)
        logger.warning("%s Continuing because strict verification is off.", message)
        return

    expected_size = pinned.get("size")
    actual_size = os.path.getsize(filepath)
    if expected_size and actual_size != expected_size:
        raise ModelIntegrityError(
            f"{filename} is {actual_size} bytes but {expected_size} bytes were expected. "
            f"The download is incomplete or the file was replaced upstream."
        )

    actual_sha256 = sha256_file(filepath)
    if actual_sha256 != pinned["sha256"]:
        raise ModelIntegrityError(
            f"SHA256 mismatch for {filename}: expected {pinned['sha256']}, "
            f"got {actual_sha256}. The download was corrupted or tampered with."
        )

    logger.info("Verified %s against its pinned SHA256 digest", filename)


def ensure_trusted_model_url(url: str) -> None:
    """
    Check that a model download URL is HTTPS on a known model host.

    Raises:
        ModelIntegrityError: If the scheme is not HTTPS or the host is unknown.
    """
    parsed = urlparse(url)
    if parsed.scheme != "https":
        raise ModelIntegrityError(f"Refusing to download a model over {parsed.scheme or 'no'}://")
    hostname = (parsed.hostname or "").lower()
    if hostname not in TRUSTED_MODEL_HOSTS:
        raise ModelIntegrityError(
            f"Refusing to download a model from untrusted host {hostname!r}. "
            f"Trusted hosts: {', '.join(sorted(TRUSTED_MODEL_HOSTS))}."
        )


def safe_extract_zip(zip_path: str, dest_dir: str) -> None:
    """
    Extract a model archive, refusing members that escape ``dest_dir``.

    ``zipfile.extractall`` resolves member names relative to the destination but
    does not reject absolute paths, ``../`` traversal or symlink entries, any of
    which let a hostile archive write over files elsewhere in the home directory.

    Raises:
        ModelIntegrityError: If any member escapes the destination, is a symlink,
            or if the archive expands beyond MAX_ARCHIVE_EXPANDED_BYTES.
    """
    dest_root = Path(dest_dir).resolve()
    total_expanded = 0

    with zipfile.ZipFile(zip_path, "r") as archive:
        for member in archive.infolist():
            name = member.filename
            if name.startswith("/") or name.startswith("\\") or Path(name).is_absolute():
                raise ModelIntegrityError(f"Archive member has an absolute path: {name!r}")

            target = (dest_root / name).resolve()
            if target != dest_root and dest_root not in target.parents:
                raise ModelIntegrityError(f"Archive member escapes the models directory: {name!r}")

            # The upper 4 bits of the high half of external_attr hold the Unix
            # file type; 0xA is a symlink, which could redirect a later write.
            if (member.external_attr >> 16) & 0xF000 == 0xA000:
                raise ModelIntegrityError(f"Archive member is a symlink: {name!r}")

            total_expanded += member.file_size
            if total_expanded > MAX_ARCHIVE_EXPANDED_BYTES:
                raise ModelIntegrityError(
                    f"Archive expands to more than "
                    f"{MAX_ARCHIVE_EXPANDED_BYTES // (1024 ** 3)} GiB; refusing to extract."
                )

        archive.extractall(dest_root)
