#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUTPUT="$REPO_ROOT/install.sh"
ORDER_FILE="$SCRIPT_DIR/build.order"
HEADER='#!/bin/bash
# Vocalinux Installer
# This script installs the Vocalinux application and its dependencies

set -e  # Exit on error

# Keep the venv isolated from ~/.local site packages while still allowing
# --system-site-packages to expose distro-provided GTK/PyGObject bindings.
export PYTHONNOUSERSITE=1

# Auto-generated by installer/build.sh — DO NOT EDIT directly.
# Source modules live in installer/lib/ and installer/phases/.
# ponytail: regeneration is deterministic; rerun `installer/build.sh build` after edits.'

cmd_build() {
    local tmp
    tmp=$(mktemp)
    {
        echo "$HEADER"
        echo ""
        while IFS= read -r module; do
            [[ -z "$module" || "$module" == \#* ]] && continue
            local path="$SCRIPT_DIR/$module"
            if [[ ! -f "$path" ]]; then
                echo "ERROR: module not found: $path" >&2
                rm -f "$tmp"
                exit 1
            fi
            echo "# >>> begin: $module >>>"
            cat "$path"
            echo ""
            echo "# <<< end: $module <<<"
        done < "$ORDER_FILE"
    } > "$tmp"
    if ! bash -n "$tmp" 2>/dev/null; then
        echo "ERROR: generated install.sh has syntax errors" >&2
        rm -f "$tmp"
        exit 1
    fi
    mv "$tmp" "$OUTPUT"
    chmod +x "$OUTPUT"
    echo "Built $OUTPUT ($(wc -l < "$OUTPUT") lines)"
}

cmd_verify() {
    bash -n "$OUTPUT" || { echo "FAIL: install.sh syntax error"; exit 1; }
    local regen
    regen=$(mktemp)
    {
        echo "$HEADER"
        echo ""
        while IFS= read -r module; do
            [[ -z "$module" || "$module" == \#* ]] && continue
            echo "# >>> begin: $module >>>"
            cat "$SCRIPT_DIR/$module"
            echo ""
            echo "# <<< end: $module <<<"
        done < "$ORDER_FILE"
    } > "$regen"
    if ! diff -q "$OUTPUT" "$regen" >/dev/null 2>&1; then
        echo "FAIL: install.sh is stale; run installer/build.sh build"
        diff -u "$OUTPUT" "$regen" | head -80
        rm -f "$regen"
        exit 1
    fi
    rm -f "$regen"
    echo "OK: install.sh is in sync"
}

cmd_clean() {
    rm -f "$OUTPUT"
    echo "Removed $OUTPUT"
}

case "${1:-build}" in
    build) cmd_build ;;
    verify) cmd_verify ;;
    clean) cmd_clean ;;
    *) echo "Usage: $0 {build|verify|clean}" >&2; exit 1 ;;
esac
